"""initial migration

Revision ID: 21128e2e2d7e
Revises: e96e68484b93
Create Date: 2018-04-23 03:32:09.896046

"""

# revision identifiers, used by Alembic.
revision = '21128e2e2d7e'
down_revision = 'e96e68484b93'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
