"""initial migration

Revision ID: ce23d4b57e36
Revises: 4c6cd7da7f62
Create Date: 2018-04-09 22:27:08.846202

"""

# revision identifiers, used by Alembic.
revision = 'ce23d4b57e36'
down_revision = '4c6cd7da7f62'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
