"""initial migration

Revision ID: e96e68484b93
Revises: ce23d4b57e36
Create Date: 2018-04-10 00:18:40.488427

"""

# revision identifiers, used by Alembic.
revision = 'e96e68484b93'
down_revision = 'ce23d4b57e36'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
